<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('client')->insert([
            [
                'firstName' => 'Marko',
                'lastName' => 'Marković',
                'gender' => 'Muški',
                'email' => 'marko.markovic@example.com',
                'phone' => '111222333',
                'dateOfBirth' => '1985-03-12',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Ana',
                'lastName' => 'Anić',
                'gender' => 'Ženski',
                'email' => 'ana.anic@example.com',
                'phone' => '444555666',
                'dateOfBirth' => '1991-08-24',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Petar',
                'lastName' => 'Petrović',
                'gender' => 'Muški',
                'email' => 'petar.petrovic@example.com',
                'phone' => '777888999',
                'dateOfBirth' => '1987-11-30',
                'status' => 'Neaktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Milica',
                'lastName' => 'Milić',
                'gender' => 'Ženski',
                'email' => 'milica.milic@example.com',
                'phone' => '222333444',
                'dateOfBirth' => '1994-07-19',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Vladimir',
                'lastName' => 'Vuković',
                'gender' => 'Muški',
                'email' => 'vladimir.vukovic@example.com',
                'phone' => '555666777',
                'dateOfBirth' => '1983-02-03',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Sanja',
                'lastName' => 'Savić',
                'gender' => 'Ženski',
                'email' => 'sanja.savic@example.com',
                'phone' => '888999000',
                'dateOfBirth' => '1990-09-10',
                'status' => 'Neaktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Luka',
                'lastName' => 'Lukić',
                'gender' => 'Muški',
                'email' => 'luka.lukic@example.com',
                'phone' => '111333555',
                'dateOfBirth' => '1988-12-05',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Tanja',
                'lastName' => 'Todorović',
                'gender' => 'Ženski',
                'email' => 'tanja.todorovic@example.com',
                'phone' => '444222888',
                'dateOfBirth' => '1993-06-21',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Stefan',
                'lastName' => 'Stefanović',
                'gender' => 'Muški',
                'email' => 'stefan.stefanovic@example.com',
                'phone' => '666444333',
                'dateOfBirth' => '1982-10-15',
                'status' => 'Neaktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Jelena',
                'lastName' => 'Jovanović',
                'gender' => 'Ženski',
                'email' => 'jelena.jovanovic@example.com',
                'phone' => '999888777',
                'dateOfBirth' => '1995-01-28',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Milan',
                'lastName' => 'Milanović',
                'gender' => 'Muški',
                'email' => 'milan.milanovic@example.com',
                'phone' => '555444333',
                'dateOfBirth' => '1989-07-14',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Marija',
                'lastName' => 'Marinković',
                'gender' => 'Ženski',
                'email' => 'marija.marinkovic@example.com',
                'phone' => '222111000',
                'dateOfBirth' => '1991-04-29',
                'status' => 'Neaktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Nikola',
                'lastName' => 'Nikolić',
                'gender' => 'Muški',
                'email' => 'nikola.nikolic@example.com',
                'phone' => '333222111',
                'dateOfBirth' => '1992-08-07',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Teodora',
                'lastName' => 'Teodorović',
                'gender' => 'Ženski',
                'email' => 'teodora.teodorovic@example.com',
                'phone' => '888111222',
                'dateOfBirth' => '1986-05-19',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Andrej',
                'lastName' => 'Andrejvić',
                'gender' => 'Muški',
                'email' => 'andrej.andrejvic@example.com',
                'phone' => '444777555',
                'dateOfBirth' => '1994-11-30',
                'status' => 'Neaktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Biljana',
                'lastName' => 'Biljković',
                'gender' => 'Ženski',
                'email' => 'biljana.biljkovic@example.com',
                'phone' => '222666444',
                'dateOfBirth' => '1993-02-15',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Radovan',
                'lastName' => 'Radović',
                'gender' => 'Muški',
                'email' => 'radovan.radovic@example.com',
                'phone' => '999000888',
                'dateOfBirth' => '1981-06-03',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Diana',
                'lastName' => 'Dijaković',
                'gender' => 'Ženski',
                'email' => 'diana.dijakovic@example.com',
                'phone' => '111444222',
                'dateOfBirth' => '1988-09-26',
                'status' => 'Neaktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Veselin',
                'lastName' => 'Veselinović',
                'gender' => 'Muški',
                'email' => 'veselin.veselinovic@example.com',
                'phone' => '777111888',
                'dateOfBirth' => '1984-03-17',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'firstName' => 'Svetlana',
                'lastName' => 'Svetković',
                'gender' => 'Ženski',
                'email' => 'svetlana.svetkovic@example.com',
                'phone' => '222999444',
                'dateOfBirth' => '1989-12-21',
                'status' => 'Aktivan',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        $client = DB::table('client')->get();

        foreach ($client as $cl) {
            DB::table('feerecords')->insert([
                'clientID' => $cl->id,
                'dateOfPayment' => now(),  
                'dateExpiry' => now()->addMonths(1),  
                'membershipFee' => 50.00,  
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
